FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv

WORKDIR /app

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy
RUN mkdir ./output
                                    
COPY [ "starter.py", "./" ]



EXPOSE 9696 

ENTRYPOINT [ "python3", "starter.py" ]

CMD  ["2023", "5"]