channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=22.3.1
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.0.0
  - lz4==4.3.3
  - numpy==1.26.4
  - packaging==23.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.13.0
name: mlflow-env
